/// Flutter icons Chesttypes
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Chesttypes
///      fonts:
///       - asset: fonts/Chesttypes.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Chesttypes {
  Chesttypes._();

  static const _kFontFam = 'Chesttypes';
  static const String _kFontPkg = null;

  static const IconData flat = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData round = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keel = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData co2_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
